# Generated by Django 5.1 on 2024-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_reader_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('numbers', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Номер класса')),
                ('classroom_teacher', models.CharField(max_length=100, verbose_name='Классный руководитель')),
                ('email_teacher', models.EmailField(max_length=254, verbose_name='Почта классного руководителя')),
            ],
        ),
    ]
