# Generated by Django 5.1 on 2024-08-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historybook',
            options={'verbose_name': 'Формуляр', 'verbose_name_plural': 'Формуляр'},
        ),
        migrations.AlterField(
            model_name='historybook',
            name='data_of_capture',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='historybook',
            name='data_of_return',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='historybook',
            name='extradition',
            field=models.BooleanField(default=False, verbose_name='Выдача'),
        ),
    ]
