# Generated by Django 5.1 on 2024-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_historybook_data_of_capture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historybook',
            name='aaa',
            field=models.CharField(default='dd', max_length=111),
        ),
    ]
