# Generated by Django 5.1 on 2024-08-15 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_historybook_aaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybook',
            name='data_of_capture',
            field=models.CharField(default=datetime.date, max_length=20, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='historybook',
            name='data_of_return',
            field=models.CharField(default=datetime.date, max_length=20, verbose_name='Дата возврата'),
        ),
    ]
