# Generated by Django 5.1 on 2024-08-15 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_historybook_data_of_capture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybook',
            name='data_of_capture',
            field=models.CharField(default=datetime.datetime(2024, 8, 15, 21, 11, 53, 730168), max_length=20, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='historybook',
            name='data_of_return',
            field=models.CharField(default=datetime.datetime(2024, 8, 15, 21, 11, 53, 730168), max_length=20, verbose_name='Дата возврата'),
        ),
    ]
