# Generated by Django 5.1 on 2024-08-15 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_historybook_data_of_capture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybook',
            name='data_of_capture',
            field=models.CharField(default=datetime.date(2024, 8, 15), max_length=20, verbose_name='Дата выдачи'),
        ),
    ]
