# Generated by Django 5.1 on 2024-08-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_historybook_data_of_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybook',
            name='extradition',
            field=models.BooleanField(default=True, verbose_name='Выдача'),
        ),
    ]
