# Generated by Django 5.1 on 2024-08-20 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_historybook_extradition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybook',
            name='data_of_capture',
            field=models.CharField(default=datetime.date(2024, 8, 20), max_length=20, verbose_name='Дата выдачи'),
        ),
    ]
